from pathlib import Path
p=Path('/tmp/mechanic-input-concept/concept.js');s=p.read_text();s=s.replace("import * as T from './three.module.js';","import * as T from './three.module.js';\nimport {createDial,createButton,designs} from './parts.js';")
a=s.index('const dial=new T.Group()');b=s.index('const controller=',a)
s=s[:a]+'''let selectedSize=5;
let dialPart=createDial(selectedSize),buttonPart=createButton(selectedSize),dial=dialPart.group,button=buttonPart.group;
dial.position.set(-1.25,0,.6);button.position.set(.2,0,1);scene.add(dial,button);
const family=new T.Group();scene.add(family);family.visible=false;const familyParts=[];
for(let [i,cm] of [5,10,25].entries()){let d=createDial(cm),b=createButton(cm),x=[-1.22,-.38,.95][i];d.group.position.set(x,0,-.55);b.group.position.set(x,0,.7);family.add(d.group,b.group);familyParts.push({d,b});label3(family,cm+' CM / '+designs[cm].name,x,.005,-1.22,'#a9becb',.08);}
''' + s[b:]
a=s.index('wire([[-1.25');b=s.index('const floor=',a)
s=s[:a]+'''function refreshLinks(){for(let o of [...links.children]){links.remove(o);o.geometry.dispose()}let s=designs[selectedSize].size;wire([[-1.25,s*.18,.6+s*.42],[-1.35,.04,1.32],[-.6,.04,1.48],[-.50,.04,-.1],[-.23,.20,-.30]],aglow);wire([[.2,s*.18,1+s*.42],[.65,.04,1.5],[.85,.04,.8],[.82,.04,-.1],[.55,.20,-.3]],mglow);wire([[-.3,.28,-.7],[-.6,.06,-.8],[-1.15,.20,-1.13]],cglow);wire([[.7,.28,-.7],[1,.06,-.85],[1.55,.20,-.7]],cglow)}refreshLinks();
''' + s[b:]
s=s.replace('new T.GridHelper(30,120,','new T.GridHelper(30,30,')
s=s.replace('rotor.rotation.y=-(value/100-.5)*Math.PI*1.5;arm.rotation.y=-angle*Math.PI/180;cap.position.y=physical?.355:.44;',"dialPart.update(value);buttonPart.update(toggle?latched:physical);for(let p of familyParts){p.d.update(value);p.b.update(toggle?latched:physical)}arm.rotation.y=-angle*Math.PI/180;")
s=s.replace('window.conceptState={value,angle',"window.conceptState={selectedSize,capY:buttonPart.cap.position.y,capRest:buttonPart.rest,capTravel:buttonPart.travel,litTicks:dialPart.ticks.filter(t=>t.material.emissive).length,label:$('#label-text').value,labelMeshes:buttonPart.labelRoot.children.length,value,angle")
a=s.index('let target=');b=s.index('let ray=',a)
s=s[:a]+'''let target=new T.Vector3(0,.05,.32),desired=target.clone(),radius=7.8,wantedRadius=7.8,azimuth=.32,elevation=.93,view='all';
function setView(v){view=v;dial.visible=v==='all'||v==='dial';button.visible=v==='all'||v==='button';family.visible=v==='family';controller.visible=steering.visible=motor.visible=v==='all';links.visible=v==='all'&&$('#wires').classList.contains('active');document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===v));desired.copy(v==='dial'?dial.position:v==='button'?button.position:new T.Vector3(0,0,.2));desired.y=(v==='dial'||v==='button')?designs[selectedSize].height*.4:.12;wantedRadius=v==='all'?7.8:v==='family'?6.4:designs[selectedSize].size*3.4;azimuth=.32;elevation=.83;$('#hint').textContent=v==='family'?'TRUE RELATIVE SCALE · 25 cm floor grid · Each size has its own construction':v==='all'?'Drag the dial · Hold the button · Drag empty space to orbit · Scroll to zoom':'Drag empty space to inspect all sides · Scroll to zoom · Interact with the part';}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function describe(){let d=designs[selectedSize];$('#dial-description').textContent=d.dial;$('#button-description').textContent=d.button;document.querySelectorAll('.size-caption').forEach(e=>e.textContent=selectedSize+' × '+selectedSize+' CM FOOTPRINT · '+d.name);$('#selected-design').textContent=selectedSize+' CM / '+d.name;}
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{scene.remove(dial,button);for(let p of [dial,button])p.traverse(o=>o.geometry?.dispose());selectedSize=Number(b.dataset.size);dialPart=createDial(selectedSize);buttonPart=createButton(selectedSize);dial=dialPart.group;button=buttonPart.group;dial.position.set(-1.25,0,.6);button.position.set(.2,0,1);scene.add(dial,button);buttonPart.setLabel($('#label-text').value);refreshLinks();document.querySelectorAll('[data-size]').forEach(e=>e.classList.toggle('active',e===b));describe();setView(view==='family'?'dial':view);update()});
let labelTimer;$('#label-text').oninput=()=>{clearTimeout(labelTimer);labelTimer=setTimeout(()=>{let text=$('#label-text').value;buttonPart.setLabel(text);for(let p of familyParts)p.b.setLabel(text);update()},150)};
$('#clear-label').onclick=()=>{$('#label-text').value='';$('#label-text').oninput()};document.querySelectorAll('[data-glyph]').forEach(b=>b.onclick=()=>{$('#label-text').value=b.dataset.glyph;$('#label-text').oninput()});
''' +s[b:]
s=s.replace('Math.max(1.5,Math.min(10,wantedRadius+e.deltaY*.005))','Math.max(.35,Math.min(10,wantedRadius+e.deltaY*wantedRadius*.001))')
s=s.replace('update();resize();requestAnimationFrame(frame);window.conceptReady=true;',"describe();update();setView('family');resize();requestAnimationFrame(frame);window.conceptReady=true;")
p.write_text(s)
p=Path('/tmp/mechanic-input-concept/index.html');s=p.read_text().replace('DESIGN STUDY 01','DESIGN STUDY 02').replace('Give your machine a cockpit.','Built for fingers. Or heavy gloves.')
s=s.replace('<button id="wires"', '<button data-view="family">Size family</button><button id="wires"')
s=s.replace('<div id="error"></div>','''<div class="size-tools"><span id="selected-design">5 CM / PANEL</span><button data-size="5" class="active">5 × 5 cm</button><button data-size="10">10 × 10 cm</button><button data-size="25">25 × 25 cm</button></div><div id="error"></div>''')
s=s.replace('<p>Scalloped grip. Exposed spindle. Broken protective hoop. An amber pointer you can read from the driver’s seat.</p>','<p id="dial-description"></p>').replace('<p>Broad floating cap. Twin guard rails. Visible spring and press travel. A mint seam lights while the signal is active.</p>','<p id="button-description"></p>').replace('<div class="tag">1 × 1 × 1 BLOCK ENVELOPE · 25 CM</div>','<div class="tag size-caption"></div>')
s=s.replace('<section><div class="eyebrow">CONNECTED INPUTS</div>','''<section class="label-editor"><div class="eyebrow">BUTTON FACE / EMBOSSED LABEL</div><div style="display:flex;gap:6px"><input id="label-text" aria-label="Button Unicode label" placeholder="Blank · type any Unicode sign" maxlength="16"><button id="clear-label">Clear</button></div><div class="glyphs"><button data-glyph="↑">↑</button><button data-glyph="⏻">⏻</button><button data-glyph="⚙">⚙</button><button data-glyph="停">停</button><span>Raised geometry · system glyphs</span></div></section><section><div class="eyebrow">CONNECTED INPUTS</div>''')
s=s.replace('</style>','''.size-tools{position:absolute;top:88px;left:24px;display:flex;gap:8px;align-items:center}.size-tools span{color:#8fa6b6;font-size:10px;letter-spacing:1px;margin-right:10px}.size-tools button{font-size:10px;padding:7px 10px}.label-editor input{min-width:0;width:100%;background:#10212b;border:1px solid #34505d;color:#dce9f2;padding:8px;border-radius:4px}.glyphs{display:flex;align-items:center;gap:6px;margin-top:7px}.glyphs button{padding:3px 8px;font-size:15px}.glyphs span{font-size:8px;color:#7895a5}.scene-top h2{font-size:24px}.scene-top{gap:10px}.view-buttons{flex-wrap:wrap;justify-content:end}aside .label-editor{margin-top:12px;padding-top:10px}aside section{margin-top:10px;padding-top:10px}aside .mapping{padding:8px;margin-top:7px}aside .mapping .title{margin-bottom:7px}aside .small-row{margin-top:6px}aside .hold{padding:9px;margin-top:7px}aside .note{line-height:1.55}.live{white-space:nowrap}@media(max-width:1100px){.size-tools{top:115px}.scene-top h2{font-size:20px}}
</style>''')
p.write_text(s)
