[package]
name = "mechanic-bench"
default-run = "mechanic-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy_math.workspace = true
mechanic-core.workspace = true
mechanic-physics.workspace = true
mechanic-gpu.workspace = true
mechanic-world.workspace = true
pollster.workspace = true
ron.workspace = true
serde_json.workspace = true
wgpu.workspace = true

[lints]
workspace = true
